require 'user.packer'
require 'user.notify'
require 'user.nvim-tree'
require 'user.lspconfig'
require 'user.mason'
require 'user.treesitter'
require 'user.reload'
require 'user.comment'
require 'user.buffers'
require 'user.status'
require 'user.git'

require 'user.theme'

require 'user.keymaps'
require 'user.options'
