require 'user.packer'
require 'user.notify'
require 'user.nvim-tree'
require 'user.lsp'
require 'user.treesitter'
require 'user.comment'
require 'user.buffers'
require 'user.status'
require 'user.git'
require 'user.telescope'
require 'user.theme'
require 'user.keymaps'
require 'user.options'

