vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.list = true
vim.opt.listchars = { tab = '▸ ', trail = '·' }
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.winblend = 0
vim.opt.background = 'dark'
vim.opt.scrolloff = 9999
vim.opt.timeoutlen = 350
vim.opt.ttimeoutlen = 0
vim.g.loaded_netrw = ' '
vim.g.loaded_netrwPlugin = ' '
vim.g.loaded_zipPlugin = 1
vim.g.loaded_zip = 1
